spring:
  application:
    name: transaction-authorizer
  messages:
    basename: messages
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/authorizer
    username: itau
    password: desafio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  springdoc:
    swagger-ui:
      enabled: true

  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

logging:
  level:
    github.ariedotme: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  springdoc:
    swagger-ui:
      enabled: false
  cloud:
    aws:
      region:
        static: sa-east-1

logging:
  level:
    github.ariedotme: INFO

management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      enabled: false
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/authorizer
#    username: itau
#    password: desafio
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#  cloud:
#    aws:
#      credentials:
#        access-key: test
#        secret-key: test
#      region:
#        static: sa-east-1
#      sqs:
#        endpoint: http://localhost:4566